
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

<System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
<System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")> _
Partial Friend NotInheritable Class Settings
   Inherits Global.System.Configuration.ApplicationSettingsBase

   Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings)

   Public Shared ReadOnly Property [Default]() As Settings
      Get
         Return defaultInstance
      End Get
   End Property
End Class