//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leadtools.Dicom.Server.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leadtools.Dicom.Server.Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap ActivityReports {
            get {
                object obj = ResourceManager.GetObject("ActivityReports", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add AE Title.
        /// </summary>
        internal static string AddAeTitle {
            get {
                return ResourceManager.GetString("AddAeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin Options.
        /// </summary>
        internal static string AddinOptions {
            get {
                return ResourceManager.GetString("AddinOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addin:.
        /// </summary>
        internal static string AddInTimeoutLabel {
            get {
                return ResourceManager.GetString("AddInTimeoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Server.
        /// </summary>
        internal static string AddNewServer {
            get {
                return ResourceManager.GetString("AddNewServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedTabPageLabel {
            get {
                return ResourceManager.GetString("AdvancedTabPageLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AeTitleAdd_Image {
            get {
                object obj = ResourceManager.GetObject("AeTitleAdd_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AeTitleDelete_Image {
            get {
                object obj = ResourceManager.GetObject("AeTitleDelete_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AeTitleEdit_Image {
            get {
                object obj = ResourceManager.GetObject("AeTitleEdit_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE Title.
        /// </summary>
        internal static string AeTitleLabel {
            get {
                return ResourceManager.GetString("AeTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AE Titles.
        /// </summary>
        internal static string AeTitleTabLabel {
            get {
                return ResourceManager.GetString("AeTitleTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Anonymous.
        /// </summary>
        internal static string AllowAnonymousLabel {
            get {
                return ResourceManager.GetString("AllowAnonymousLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEADTOOLS DICOM Server Manager - C#.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association:.
        /// </summary>
        internal static string AssociationLabel {
            get {
                return ResourceManager.GetString("AssociationLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap BrowseFolder_Image {
            get {
                object obj = ResourceManager.GetObject("BrowseFolder_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ClientAssociation_Image {
            get {
                object obj = ResourceManager.GetObject("ClientAssociation_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ClientDisconnect_Image {
            get {
                object obj = ResourceManager.GetObject("ClientDisconnect_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string ClientsTabLabel {
            get {
                return ResourceManager.GetString("ClientsTabLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client:.
        /// </summary>
        internal static string ClientTimeoutLabel {
            get {
                return ResourceManager.GetString("ClientTimeoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Time.
        /// </summary>
        internal static string ConnectTimeColumnLabel {
            get {
                return ResourceManager.GetString("ConnectTimeColumnLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap DefaultOptionImage {
            get {
                object obj = ResourceManager.GetObject("DefaultOptionImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Display Name:.
        /// </summary>
        internal static string DisplayNameLabel {
            get {
                return ResourceManager.GetString("DisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit AE Title.
        /// </summary>
        internal static string EditAeTitle {
            get {
                return ResourceManager.GetString("EditAeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Server.
        /// </summary>
        internal static string EditServer {
            get {
                return ResourceManager.GetString("EditServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Service Log.
        /// </summary>
        internal static string EnableLogLabel {
            get {
                return ResourceManager.GetString("EnableLogLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Eval_Image {
            get {
                object obj = ResourceManager.GetObject("Eval_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Help_Image {
            get {
                object obj = ResourceManager.GetObject("Help_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name:.
        /// </summary>
        internal static string HostnameLabel {
            get {
                return ResourceManager.GetString("HostnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname/IPAddress.
        /// </summary>
        internal static string HostNamePortColumnLabel {
            get {
                return ResourceManager.GetString("HostNamePortColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Class UID:.
        /// </summary>
        internal static string ImplementationClassLabel {
            get {
                return ResourceManager.GetString("ImplementationClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implementation Version Name:.
        /// </summary>
        internal static string ImplementationVersionNameLabel {
            get {
                return ResourceManager.GetString("ImplementationVersionNameLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap InvalidKey_Image {
            get {
                object obj = ResourceManager.GetObject("InvalidKey_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddressColumnLabel {
            get {
                return ResourceManager.GetString("IPAddressColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:.
        /// </summary>
        internal static string IPAddressLabel {
            get {
                return ResourceManager.GetString("IPAddressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Action.
        /// </summary>
        internal static string LastActionColumnLabel {
            get {
                return ResourceManager.GetString("LastActionColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Clients:.
        /// </summary>
        internal static string MaxClientsLabel {
            get {
                return ResourceManager.GetString("MaxClientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Pdu Length:.
        /// </summary>
        internal static string MaxPduLabel {
            get {
                return ResourceManager.GetString("MaxPduLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Delay.
        /// </summary>
        internal static string NoDelayLabel {
            get {
                return ResourceManager.GetString("NoDelayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap PauseService_Image {
            get {
                object obj = ResourceManager.GetObject("PauseService_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Properties_Image {
            get {
                object obj = ResourceManager.GetObject("Properties_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties:.
        /// </summary>
        internal static string PropertyLabel {
            get {
                return ResourceManager.GetString("PropertyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Buffer:.
        /// </summary>
        internal static string ReceiveBufferLabel {
            get {
                return ResourceManager.GetString("ReceiveBufferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect:.
        /// </summary>
        internal static string ReconnectTimeoutLabel {
            get {
                return ResourceManager.GetString("ReconnectTimeoutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Port.
        /// </summary>
        internal static string SecurePortColumnLabel {
            get {
                return ResourceManager.GetString("SecurePortColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Buffer:.
        /// </summary>
        internal static string SendBufferLabel {
            get {
                return ResourceManager.GetString("SendBufferLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address:.
        /// </summary>
        internal static string ServerIpLabel {
            get {
                return ResourceManager.GetString("ServerIpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        internal static string ServerLabel {
            get {
                return ResourceManager.GetString("ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string ServerPortLabel {
            get {
                return ResourceManager.GetString("ServerPortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Secure.
        /// </summary>
        internal static string ServerSecureLabel {
            get {
                return ResourceManager.GetString("ServerSecureLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ServiceAdd_Image {
            get {
                object obj = ResourceManager.GetObject("ServiceAdd_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServiceDelete_Image {
            get {
                object obj = ResourceManager.GetObject("ServiceDelete_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ServiceEdit_Image {
            get {
                object obj = ResourceManager.GetObject("ServiceEdit_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTabPageLabel {
            get {
                return ResourceManager.GetString("SettingsTabPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket Options.
        /// </summary>
        internal static string SocketOptionsGroupBoxLabel {
            get {
                return ResourceManager.GetString("SocketOptionsGroupBoxLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap start_all {
            get {
                object obj = ResourceManager.GetObject("start_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Mode:.
        /// </summary>
        internal static string StartModeLabel {
            get {
                return ResourceManager.GetString("StartModeLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StartService_Image {
            get {
                object obj = ResourceManager.GetObject("StartService_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stop_all {
            get {
                object obj = ResourceManager.GetObject("stop_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StopService_Image {
            get {
                object obj = ResourceManager.GetObject("StopService_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary Directory:.
        /// </summary>
        internal static string TemporaryDirectoryLabel {
            get {
                return ResourceManager.GetString("TemporaryDirectoryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeouts (Seconds).
        /// </summary>
        internal static string TimeoutGroupBoxLabel {
            get {
                return ResourceManager.GetString("TimeoutGroupBoxLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap ValidKey_Image {
            get {
                object obj = ResourceManager.GetObject("ValidKey_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Association.
        /// </summary>
        internal static string ViewAssociation {
            get {
                return ResourceManager.GetString("ViewAssociation", resourceCulture);
            }
        }
    }
}
