'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")> _
Partial Friend NotInheritable Class Settings
   Inherits Global.System.Configuration.ApplicationSettingsBase

   Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings)

   Public Shared ReadOnly Property [Default]() As Settings
      Get
         Return defaultInstance
      End Get
   End Property

   <Global.System.Configuration.UserScopedSettingAttribute(), _
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
    Global.System.Configuration.DefaultSettingValueAttribute("")> _
   Public Property OcrEngineType() As String
      Get
         Return CType(Me("OcrEngineType"), String)
      End Get
      Set(value As String)
         Me("OcrEngineType") = value
      End Set
   End Property

   <Global.System.Configuration.UserScopedSettingAttribute(), _
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
    Global.System.Configuration.DefaultSettingValueAttribute("True")> _
   Public Property FirstRun() As Boolean
      Get
         Return CType(Me("FirstRun"), Boolean)
      End Get
      Set(value As Boolean)
         Me("FirstRun") = value
      End Set
   End Property

   <Global.System.Configuration.UserScopedSettingAttribute(), _
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
    Global.System.Configuration.DefaultSettingValueAttribute("")> _
   Public Property MasterFormsPath() As String
      Get
         Return CType(Me("MasterFormsPath"), String)
      End Get
      Set(value As String)
         Me("MasterFormsPath") = value
      End Set
   End Property

   <Global.System.Configuration.UserScopedSettingAttribute(), _
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
    Global.System.Configuration.DefaultSettingValueAttribute("")> _
   Public Property SourceFolder() As String
      Get
         Return CType(Me("SourceFolder"), String)
      End Get
      Set(value As String)
         Me("SourceFolder") = value
      End Set
   End Property

   <Global.System.Configuration.UserScopedSettingAttribute(), _
    Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
    Global.System.Configuration.DefaultSettingValueAttribute("True")> _
   Public Property ShowAgain() As String
      Get
         Return CType(Me("ShowAgain"), String)
      End Get
      Set(value As String)
         Me("ShowAgain") = value
      End Set
   End Property
End Class
