'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34003
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
   <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()> _
    Friend Module Resources

      Private resourceMan As Global.System.Resources.ResourceManager

      Private resourceCulture As Global.System.Globalization.CultureInfo

      '''<summary>
      '''  Returns the cached ResourceManager instance used by this class.
      '''</summary>
      <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
      Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
         Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
               Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OcrMultiEngineDemo.Resources", GetType(Resources).Assembly)
               resourceMan = temp
            End If
            Return resourceMan
         End Get
      End Property

      '''<summary>
      '''  Overrides the current thread's CurrentUICulture property for all
      '''  resource lookups using this strongly typed resource class.
      '''</summary>
      <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
      Friend Property Culture() As Global.System.Globalization.CultureInfo
         Get
            Return resourceCulture
         End Get
         Set(value As Global.System.Globalization.CultureInfo)
            resourceCulture = value
         End Set
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property AutoZoneDocument() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("AutoZoneDocument", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property AutoZonePage() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("AutoZonePage", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DeletePage() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DeletePage", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DeleteZone() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DeleteZone", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property DrawZoneMode() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("DrawZoneMode", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property FitPage() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("FitPage", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property FitPageWidth() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("FitPageWidth", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property InsertPage() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("InsertPage", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MoveLeft() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MoveLeft", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MovePageDown() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MovePageDown", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MovePageUp() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MovePageUp", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MoveRight() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MoveRight", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property MoveTop() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("MoveTop", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property NewDocument() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("NewDocument", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property NextPage() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("NextPage", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property OpenDocument() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("OpenDocument", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property PanMode() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("PanMode", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property PreviousPage() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("PreviousPage", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property RecognizeAllPages() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("RecognizeAllPages", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property RecognizePage() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("RecognizePage", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property SaveDocument() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("SaveDocument", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property SelectMode() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("SelectMode", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ShowZoneName() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ShowZoneName", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ShowZones() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ShowZones", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ZoneProperties() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ZoneProperties", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ZoomIn() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ZoomIn", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ZoomOut() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ZoomOut", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property

      '''<summary>
      '''  Looks up a localized resource of type System.Drawing.Bitmap.
      '''</summary>
      Friend ReadOnly Property ZoomSelection() As System.Drawing.Bitmap
         Get
            Dim obj As Object = ResourceManager.GetObject("ZoomSelection", resourceCulture)
            Return CType(obj, System.Drawing.Bitmap)
         End Get
      End Property
   End Module
End Namespace
