//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leadtools.Demos.Workstation.Customized.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leadtools.Demos.Workstation.Customized.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;actionsDisplayName&gt;
        ///   &lt;entry&gt;
        ///      &lt;action&gt;None&lt;/action&gt;
        ///      &lt;displayName&gt;Selección&lt;/displayName&gt;
        ///   &lt;/entry&gt;
        ///   &lt;entry&gt;
        ///      &lt;action&gt;WindowLevel&lt;/action&gt;
        ///      &lt;displayName&gt;Nivel de Ventana&lt;/displayName&gt;
        ///   &lt;/entry&gt;
        ///   &lt;entry&gt;
        ///      &lt;action&gt;Scale&lt;/action&gt;
        ///      &lt;displayName&gt;Acercamiento&lt;/displayName&gt;
        ///   &lt;/entry&gt;
        ///   &lt;entry&gt;
        ///      &lt;action&gt;Offset&lt;/action&gt;
        ///      &lt;displayName&gt;Compensar&lt;/displayName&gt;
        ///   &lt;/entry&gt;
        ///   &lt;entry&gt;
        ///      &lt;action&gt;Stack&lt;/actio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string actionName_Spanish {
            get {
                return ResourceManager.GetString("actionName_Spanish", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;WorkstationMessages&gt;
        ///  &lt;ViewerNotExistError&gt;El visor no existe.&lt;/ViewerNotExistError&gt;
        ///  &lt;ViewerNotBelongToViewError&gt;El visor no le pertenece a este panorama.&lt;/ViewerNotBelongToViewError&gt;
        ///  &lt;StudyExistsError&gt;El estudio ya existe.&lt;/StudyExistsError&gt;
        ///  &lt;VolumeLoadedError&gt;El volumen ya esta cargado.&lt;/VolumeLoadedError&gt;
        ///  &lt;LoaderNotFoundError&gt;No se ha encontrado un cargador para la serie.&lt;/LoaderNotFoundError&gt;
        ///  &lt;VolumeViewerFormattedTitle&gt;{0} Volumen&lt;/VolumeViewerF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Messages_Spanish {
            get {
                return ResourceManager.GetString("Messages_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;loaderStatusMessage&gt;
        ///   &lt;RetrievingSeries&gt;
        ///      &lt;message&gt;Recuperando la serie de imagenes...&lt;/message&gt;
        ///   &lt;/RetrievingSeries&gt;
        ///   &lt;LoadingSeries&gt;
        ///      &lt;message&gt;Cargando la serie de imagenes...&lt;/message&gt;
        ///   &lt;/LoadingSeries&gt;
        ///   &lt;CreatingSeries&gt;
        ///      &lt;message&gt;Creando la serie de celdas...&lt;/message&gt;
        ///   &lt;/CreatingSeries&gt;
        ///   &lt;LoadingImages&gt;
        ///      &lt;message&gt;Cargando imagenes...&lt;/message&gt;
        ///   &lt;/LoadingImages&gt;
        ///   &lt;LoadingTags&gt;
        ///      &lt;message&gt;Cargando etiquetas s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatusMessages_Spanish {
            get {
                return ResourceManager.GetString("StatusMessages_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;toolStripMenuProperties&gt;
        ///   &lt;SaveToolStripButton&gt;
        ///      &lt;text&gt;&amp;amp;Guardar&lt;/text&gt;
        ///      &lt;shortcutKeys&gt;None&lt;/shortcutKeys&gt;
        ///   &lt;/SaveToolStripButton&gt;
        ///   &lt;CopyToolStripButton&gt;
        ///      &lt;text&gt;&amp;amp;Copia&lt;/text&gt;
        ///      &lt;shortcutKeys&gt;None&lt;/shortcutKeys&gt;
        ///   &lt;/CopyToolStripButton&gt;
        ///   &lt;PrintToolStripButton&gt;
        ///      &lt;text&gt;&amp;amp;Imprimir&lt;/text&gt;
        ///      &lt;shortcutKeys&gt;None&lt;/shortcutKeys&gt;
        ///   &lt;/PrintToolStripButton&gt;
        ///   &lt;AnnotationsSaveLoadDropDownButton&gt;
        ///      &lt;text&gt;Guardar/Car [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Toolstrip_Spanish {
            get {
                return ResourceManager.GetString("Toolstrip_Spanish", resourceCulture);
            }
        }
    }
}
