//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobProcessorAdministratorDemo.JobService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddJobRequest", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class AddJobRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobMetadataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobId {
            get {
                return this.JobIdField;
            }
            set {
                if ((object.ReferenceEquals(this.JobIdField, value) != true)) {
                    this.JobIdField = value;
                    this.RaisePropertyChanged("JobId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobMetadata {
            get {
                return this.JobMetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.JobMetadataField, value) != true)) {
                    this.JobMetadataField = value;
                    this.RaisePropertyChanged("JobMetadata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddJobResponse", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class AddJobResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClientJobsRequest", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class GetClientJobsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetClientJobsResponse", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class GetClientJobsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] JobsIdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] JobsIds {
            get {
                return this.JobsIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.JobsIdsField, value) != true)) {
                    this.JobsIdsField = value;
                    this.RaisePropertyChanged("JobsIds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteJobRequest", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class DeleteJobRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteJobResponse", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class DeleteJobResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeletedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDeleted {
            get {
                return this.IsDeletedField;
            }
            set {
                if ((this.IsDeletedField.Equals(value) != true)) {
                    this.IsDeletedField = value;
                    this.RaisePropertyChanged("IsDeleted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbortJobRequest", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class AbortJobRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbortJobResponse", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class AbortJobResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAbortedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAborted {
            get {
                return this.IsAbortedField;
            }
            set {
                if ((this.IsAbortedField.Equals(value) != true)) {
                    this.IsAbortedField = value;
                    this.RaisePropertyChanged("IsAborted");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetJobInformationRequest", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class GetJobInformationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetJobInformationResponse", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class GetJobInformationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobProcessorAdministratorDemo.JobService.JobInformation JobInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobProcessorAdministratorDemo.JobService.JobInformation JobInformation {
            get {
                return this.JobInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.JobInformationField, value) != true)) {
                    this.JobInformationField = value;
                    this.RaisePropertyChanged("JobInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobInformation", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class JobInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobProcessorAdministratorDemo.JobService.Abort AbortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> AddedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttemptsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CompletedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FailedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobProcessorAdministratorDemo.JobService.FailureInformation FailureInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastStartedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdatedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobProcessorAdministratorDemo.JobService.Metadata MetadataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PercentageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobProcessorAdministratorDemo.JobService.JobStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobProcessorAdministratorDemo.JobService.Abort Abort {
            get {
                return this.AbortField;
            }
            set {
                if ((object.ReferenceEquals(this.AbortField, value) != true)) {
                    this.AbortField = value;
                    this.RaisePropertyChanged("Abort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> AddedTime {
            get {
                return this.AddedTimeField;
            }
            set {
                if ((this.AddedTimeField.Equals(value) != true)) {
                    this.AddedTimeField = value;
                    this.RaisePropertyChanged("AddedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Attempts {
            get {
                return this.AttemptsField;
            }
            set {
                if ((this.AttemptsField.Equals(value) != true)) {
                    this.AttemptsField = value;
                    this.RaisePropertyChanged("Attempts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CompletedTime {
            get {
                return this.CompletedTimeField;
            }
            set {
                if ((this.CompletedTimeField.Equals(value) != true)) {
                    this.CompletedTimeField = value;
                    this.RaisePropertyChanged("CompletedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FailedTime {
            get {
                return this.FailedTimeField;
            }
            set {
                if ((this.FailedTimeField.Equals(value) != true)) {
                    this.FailedTimeField = value;
                    this.RaisePropertyChanged("FailedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobProcessorAdministratorDemo.JobService.FailureInformation FailureInformation {
            get {
                return this.FailureInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.FailureInformationField, value) != true)) {
                    this.FailureInformationField = value;
                    this.RaisePropertyChanged("FailureInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastStartedTime {
            get {
                return this.LastStartedTimeField;
            }
            set {
                if ((this.LastStartedTimeField.Equals(value) != true)) {
                    this.LastStartedTimeField = value;
                    this.RaisePropertyChanged("LastStartedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdatedTime {
            get {
                return this.LastUpdatedTimeField;
            }
            set {
                if ((this.LastUpdatedTimeField.Equals(value) != true)) {
                    this.LastUpdatedTimeField = value;
                    this.RaisePropertyChanged("LastUpdatedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobProcessorAdministratorDemo.JobService.Metadata Metadata {
            get {
                return this.MetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.MetadataField, value) != true)) {
                    this.MetadataField = value;
                    this.RaisePropertyChanged("Metadata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Percentage {
            get {
                return this.PercentageField;
            }
            set {
                if ((this.PercentageField.Equals(value) != true)) {
                    this.PercentageField = value;
                    this.RaisePropertyChanged("Percentage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobProcessorAdministratorDemo.JobService.JobStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Worker {
            get {
                return this.WorkerField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerField, value) != true)) {
                    this.WorkerField = value;
                    this.RaisePropertyChanged("Worker");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Abort", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class Abort : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AbortReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MustAbortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AbortReason {
            get {
                return this.AbortReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.AbortReasonField, value) != true)) {
                    this.AbortReasonField = value;
                    this.RaisePropertyChanged("AbortReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MustAbort {
            get {
                return this.MustAbortField;
            }
            set {
                if ((this.MustAbortField.Equals(value) != true)) {
                    this.MustAbortField = value;
                    this.RaisePropertyChanged("MustAbort");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FailureInformation", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class FailureInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FailedErrorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailedMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FailedErrorID {
            get {
                return this.FailedErrorIDField;
            }
            set {
                if ((this.FailedErrorIDField.Equals(value) != true)) {
                    this.FailedErrorIDField = value;
                    this.RaisePropertyChanged("FailedErrorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailedMessage {
            get {
                return this.FailedMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedMessageField, value) != true)) {
                    this.FailedMessageField = value;
                    this.RaisePropertyChanged("FailedMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Metadata", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class Metadata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobMetadataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkerMetadataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobMetadata {
            get {
                return this.JobMetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.JobMetadataField, value) != true)) {
                    this.JobMetadataField = value;
                    this.RaisePropertyChanged("JobMetadata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkerMetadata {
            get {
                return this.WorkerMetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkerMetadataField, value) != true)) {
                    this.WorkerMetadataField = value;
                    this.RaisePropertyChanged("WorkerMetadata");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobStatus", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    public enum JobStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        New = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Queried = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Started = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aborted = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetJobRequest", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class ResetJobRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobMetadataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobMetadata {
            get {
                return this.JobMetadataField;
            }
            set {
                if ((object.ReferenceEquals(this.JobMetadataField, value) != true)) {
                    this.JobMetadataField = value;
                    this.RaisePropertyChanged("JobMetadata");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetJobResponse", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class ResetJobResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private JobProcessorAdministratorDemo.JobService.JobStatus StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobType {
            get {
                return this.JobTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTypeField, value) != true)) {
                    this.JobTypeField = value;
                    this.RaisePropertyChanged("JobType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public JobProcessorAdministratorDemo.JobService.JobStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AddJobsRequest", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01", ItemName="AddJobRequest")]
    [System.SerializableAttribute()]
    public class AddJobsRequest : System.Collections.Generic.List<JobProcessorAdministratorDemo.JobService.AddJobRequest> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddJobsResponse", Namespace="http://Leadtools.Services.JobProcessor.DataContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class AddJobsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] IdsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Ids {
            get {
                return this.IdsField;
            }
            set {
                if ((object.ReferenceEquals(this.IdsField, value) != true)) {
                    this.IdsField = value;
                    this.RaisePropertyChanged("Ids");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
    [System.SerializableAttribute()]
    public partial class JobProcessorFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorIdField;
        
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorId {
            get {
                return this.ErrorIdField;
            }
            set {
                if ((this.ErrorIdField.Equals(value) != true)) {
                    this.ErrorIdField = value;
                    this.RaisePropertyChanged("ErrorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01", ConfigurationName="JobService.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AddJob", ReplyAction="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AddJobRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(JobProcessorAdministratorDemo.JobService.JobProcessorFault), Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AddJobJobProcessorF" +
            "aultFault", Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
        JobProcessorAdministratorDemo.JobService.AddJobResponse AddJob(JobProcessorAdministratorDemo.JobService.AddJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/GetClientJob" +
            "s", ReplyAction="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/GetClientJob" +
            "sResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JobProcessorAdministratorDemo.JobService.JobProcessorFault), Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/GetClientJob" +
            "sJobProcessorFaultFault", Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
        JobProcessorAdministratorDemo.JobService.GetClientJobsResponse GetClientJobs(JobProcessorAdministratorDemo.JobService.GetClientJobsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/DeleteJob", ReplyAction="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/DeleteJobRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JobProcessorAdministratorDemo.JobService.JobProcessorFault), Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/DeleteJobClo" +
            "udFaultFault", Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
        JobProcessorAdministratorDemo.JobService.DeleteJobResponse DeleteJob(JobProcessorAdministratorDemo.JobService.DeleteJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AbortJob", ReplyAction="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AbortJobResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JobProcessorAdministratorDemo.JobService.JobProcessorFault), Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AbortJobClou" +
            "dFaultFault", Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
        JobProcessorAdministratorDemo.JobService.AbortJobResponse AbortJob(JobProcessorAdministratorDemo.JobService.AbortJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/GetJobInform" +
            "ation", ReplyAction="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/GetJobInform" +
            "ationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JobProcessorAdministratorDemo.JobService.JobProcessorFault), Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/GetJobInform" +
            "ationJobProcessorFaultFault", Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
        JobProcessorAdministratorDemo.JobService.GetJobInformationResponse GetJobInformation(JobProcessorAdministratorDemo.JobService.GetJobInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/ResetJob", ReplyAction="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/ResetJobResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JobProcessorAdministratorDemo.JobService.JobProcessorFault), Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/ResetJobClou" +
            "dFaultFault", Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
        JobProcessorAdministratorDemo.JobService.ResetJobResponse ResetJob(JobProcessorAdministratorDemo.JobService.ResetJobRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AddJobs", ReplyAction="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AddJobsRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(JobProcessorAdministratorDemo.JobService.JobProcessorFault), Action="http://Leadtools.Services.JobProcessor.ServiceContracts/2010/01/IJobService/AddJobsJobProcessor" +
            "FaultFault", Name="JobProcessorFault", Namespace="http://Leadtools.Services.JobProcessor.FaultContracts/2010/01")]
        JobProcessorAdministratorDemo.JobService.AddJobsResponse AddJobs(JobProcessorAdministratorDemo.JobService.AddJobsRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IJobServiceChannel : JobProcessorAdministratorDemo.JobService.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<JobProcessorAdministratorDemo.JobService.IJobService>, JobProcessorAdministratorDemo.JobService.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public JobProcessorAdministratorDemo.JobService.AddJobResponse AddJob(JobProcessorAdministratorDemo.JobService.AddJobRequest request) {
            return base.Channel.AddJob(request);
        }
        
        public JobProcessorAdministratorDemo.JobService.GetClientJobsResponse GetClientJobs(JobProcessorAdministratorDemo.JobService.GetClientJobsRequest request) {
            return base.Channel.GetClientJobs(request);
        }
        
        public JobProcessorAdministratorDemo.JobService.DeleteJobResponse DeleteJob(JobProcessorAdministratorDemo.JobService.DeleteJobRequest request) {
            return base.Channel.DeleteJob(request);
        }
        
        public JobProcessorAdministratorDemo.JobService.AbortJobResponse AbortJob(JobProcessorAdministratorDemo.JobService.AbortJobRequest request) {
            return base.Channel.AbortJob(request);
        }
        
        public JobProcessorAdministratorDemo.JobService.GetJobInformationResponse GetJobInformation(JobProcessorAdministratorDemo.JobService.GetJobInformationRequest request) {
            return base.Channel.GetJobInformation(request);
        }
        
        public JobProcessorAdministratorDemo.JobService.ResetJobResponse ResetJob(JobProcessorAdministratorDemo.JobService.ResetJobRequest request) {
            return base.Channel.ResetJob(request);
        }
        
        public JobProcessorAdministratorDemo.JobService.AddJobsResponse AddJobs(JobProcessorAdministratorDemo.JobService.AddJobsRequest request) {
            return base.Channel.AddJobs(request);
        }
    }
}
