//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobProcessorHostDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JobProcessorHostDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [master]
        ///GO
        ///IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N&apos;@DatabaseName@&apos;)
        ///BEGIN
        ///CREATE DATABASE [@DatabaseName@]
        ///END
        ///
        ///GO
        ///EXEC dbo.sp_dbcmptlevel @dbname=N&apos;@DatabaseName@&apos;, @new_cmptlevel=90
        ///GO
        ///IF (1 = FULLTEXTSERVICEPROPERTY(&apos;IsFullTextInstalled&apos;))
        ///begin
        ///EXEC [@DatabaseName@].[dbo].[sp_fulltext_database] @action = &apos;enable&apos;
        ///end
        ///GO
        ///ALTER DATABASE [@DatabaseName@] SET ANSI_NULL_DEFAULT OFF 
        ///GO
        ///ALTER DATABASE [@DatabaseName@] SET ANSI_NULLS OFF 
        ///GO
        ///ALTER DATABASE [@Databas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASPNetSqlReg {
            get {
                return ResourceManager.GetString("ASPNetSqlReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS ( SELECT * FROM master.dbo.syslogins where loginname = N&apos;@MachineName@\ASPNET&apos; )
        ///BEGIN
        ///	EXEC sp_grantlogin N&apos;@MachineName@\ASPNET&apos;
        ///	EXEC sp_defaultdb N&apos;@MachineName@\ASPNET&apos;, N&apos;@DatabaseName@&apos;
        ///END
        ///
        ///GO
        ///
        ///USE [@DatabaseName@]
        ///
        ///IF NOT EXISTS ( SELECT * FROM dbo.sysusers WHERE name = N&apos;ASPNET&apos; AND uid &lt; 16382 )
        ///BEGIN
        ///  EXEC sp_grantdbaccess N&apos;@MachineName@\ASPNET&apos;, N&apos;ASPNET&apos;
        ///END
        ///
        ///GO
        ///
        ///USE [@DatabaseName@]
        ///  
        ///EXEC sp_addrolemember N&apos;db_owner&apos;, N&apos;ASPNET&apos;
        ///
        ///GO
        ///.
        /// </summary>
        internal static string CreateASPNETDatabaseUser {
            get {
                return ResourceManager.GetString("CreateASPNETDatabaseUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS ( SELECT * FROM master.dbo.syslogins WHERE loginname = N&apos;@LoginName@&apos; )
        ///   EXEC sp_addlogin N&apos;@LoginName@&apos;, N&apos;@LoginPassword@&apos;, N&apos;@DatabaseName@&apos;
        ///
        ///GO
        ///
        ///USE [@DatabaseName@]
        ///if &apos;@LoginName@&apos; &lt;&gt; &apos;sa&apos;
        ///BEGIN
        ///   IF NOT EXISTS (SELECT * FROM sysusers WHERE name = N&apos;@LoginName@&apos; AND uid &lt; 16382 )
        ///   BEGIN
        ///      EXEC sp_grantdbaccess N&apos;@LoginName@&apos;, N&apos;@LoginName@&apos;
        ///   END
        ///   
        ///   EXEC sp_addrolemember N&apos;db_owner&apos;, N&apos;@LoginName@&apos;
        ///END
        ///
        ///GO
        ///.
        /// </summary>
        internal static string CreateDatabaseUser {
            get {
                return ResourceManager.GetString("CreateDatabaseUser", resourceCulture);
            }
        }
    }
}
